#!/bin/bash
#
# Jakub Majcher
# v.1.2
# 17 listopada 2023
#

i=0

cd $1
while read line
do
    array[ $i ]=$line
	(( i++ ))
done < <(ls)

element=0
for element in "${array[@]}"; do
	# Getting the orientation of a photo into a variable
	orientation=`exiftool -Orientation -S -s -ext jpg "$element"`
	datetime=`exiftool -d "[%Y.%m.%d]" -DateTimeOriginal -S -s -ext jpg "$element"`
	hours=`exiftool -d "%H-%M-%S" -DateTimeOriginal -S -s -ext jpg "$element"`
	if [ "$datetime" == "" ] && [ "$hours" == "" ]; then
		newName="$element"
	else
		newName="$datetime $hours - $element"
	fi

	# Deleting all exifs
	exiftool -ALL= "$element"

	# Setuping orientation of photo
	exiftool -Orientation="$orientation" "$element"
	
	mv "$element" "../Converted/$newName"
	mv "$element""_original" "../Original/$element""_original"
done
